language: go
install:
- sudo add-apt-repository -y ppa:masterminds/glide
- sudo apt-get update
- sudo apt-get -y install make glide
- glide update -v
matrix:
  include:
  - go: 1.6.4
    env: OPTIONS="-race"
  - go: 1.7.4
    env: COVERAGE="true" OPTIONS=""
script:
- go fmt $(go list ./... | grep -v vendor) | wc -l | grep 0
- go vet $(go list ./... | grep -v vendor)
- make
- make test
