apiVersion: storage.coreos.com/v1alpha1
kind: StorageCluster
metadata:
    name: nfs
spec:
    type: nfs
    storageNodes:
        - nodeName: node0
          directories:
              - /export
          nfs:
              size: 10Gi
        - nodeName: node1
          directories:
              - /export
          nfs:
              size: 20Gi
