apiVersion: storage.coreos.com/v1alpha1
kind: StorageCluster
metadata:
    name: gluster
spec:
    type: glusterfs
    storageNodes:
        - nodeName: ip-10-0-64-65.us-west-1.compute.internal
          storageNetwork:
            ips:
                - 10.0.64.65
          devices:
              - /dev/xvdc
          glusterfs:
              zone: 1
        - nodeName: ip-10-0-112-197.us-west-1.compute.internal
          storageNetwork:
            ips:
                - 10.0.112.197
          devices:
              - /dev/xvdc
          glusterfs:
              zone: 2
        - nodeName: ip-10-0-65-93.us-west-1.compute.internal
          storageNetwork:
            ips:
                - 10.0.65.93
          devices:
              - /dev/xvdc
          glusterfs:
              zone: 3
