kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myvol
  annotations:
    volume.beta.kubernetes.io/storage-class: gluster.qm.default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 34Gi
