apiVersion: storage.coreos.com/v1alpha1
kind: StorageCluster
metadata:
    name: mock
spec:
    type: mock
    storageNodes:
        - nodeName: node0
          directories:
              - /export
        - directories:
              - /export
          nodeSelector:
              disktype: sata
        - image: gcr.io/google_containers/pause:2.0
          nodeSelector:
              disktype: ssd
          directories:
              - /export
